# This file contains the configuration settings for the repository.

###########
##  I/O  ##
###########

directories:
  sourcedata: ./sourcedata  # READ-ONLY!!!
  derivatives: ./derivatives  # WRITE
  archive: ./archive  # WRITE

source_filenames:
  datapackage: datapackage-template.json
  corpus: fdd-v0.2.0.xlsx
  mapping: report2gpt_id_mapping.xlsx
  labels: Inter-rater_100dreams.xlsx
  spans:
    - cpicard.jsonl
    - tmatzek.jsonl

archive_metadata:
  full_name: Dream Flight Archive
  version: "0.0.1-beta"

################
##  Plotting  ##
################

palette:
  narrative: "#0c7bdc"
  observation: "#ffc20a"
  lucid: "#29c9e6"  # #29cae7
  flying: "#fca094"  # #fda094

markers:
  AlchemyForums: h
  DreamBank: o
  IDreamOfCovid: <
  IntArchivDreams: v
  LD4all: s
  LucidityInstitute: "8"
  Reddit: ^
  SDDb: "*"
  StraightDope: p
  Twitter: ">"

rc_params:
  interactive: False
  savefig.dpi: 300
  font.family: sans-serif
  font.sans-serif: Arial
  mathtext.fontset: custom
  mathtext.rm: Arial
  mathtext.it: Arial:italic
  mathtext.bf: Arial:bold
