name: nightflight
channels:
  - defaults
dependencies:
  - python=3.11
  - ipython
  - ruff
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - matplotlib
  - colorcet
  - conda-forge::spacy
  - conda-forge::frictionless
  - pip
  - pip:
    - pygamma-agreement
